use strict;

package CONFIG_VARS;
#ARCHIVO DONDE SE GUARDARAN LOS EVENTOS DEL SCRIPT
	our $LOG_FILE		=	"/tmp/log_file1";

#NOMBRE DE LA FUNCION PRINCIPAL
	our $FUNCTION_NAME	=	"main";

#MANEJADOR DE ARCHIVO
	our $FILE_HANDLER;

#UBICACION DEL ARCHIVO QUE CONTIENE LA BASE DE DATOS DE GEO::IP
	our $GEO_IP_DIR		=	"/usr/local/share/GeoIP/GeoLiteCity.dat";

#UBICACION DEL ARCHIVO QUE CONTIENE LA RELACION IP-COORDENADAS DE LAS DEPENDENCIAS DE LA UNAM
	our $GEO_IP_UNAM_DIR	=	"/PHUapi/Utils/Geo/GeoUnam.dat";
1;
